version: '3.5'

services:
  oap:
    image: apache/skywalking-oap-server:8.6.0-es7
    networks:
      - lal
    ports:
      - 11800:11800
      - 12800:12800
    environment:
      SW_STORAGE: h2
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
      SW_HEALTH_CHECKER: default
      SW_TELEMETRY: prometheus
    healthcheck:
      test: [ "CMD", "./bin/swctl", "ch" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  ui:
    image: apache/skywalking-ui:8.6.0
    networks:
      - lal
    depends_on:
      oap:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      SW_OAP_ADDRESS: http://oap:12800
    healthcheck:
      test: [ "CMD", "bash", "-c", "cat < /dev/null > /dev/tcp/127.0.0.1/8080" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  agent:
    build:
      context: .
    environment:
      SW_AGENT_NAME: lal-log4j
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: oap:11800
      SW_GRPC_LOG_SERVER_HOST: oap
      SW_GRPC_LOG_SERVER_PORT: 11800
    networks:
      - lal
    healthcheck:
      test: [ "CMD", "sh", "-c", "nc -nz 127.0.0.1 9999" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      oap:
        condition: service_healthy

  traffic:
    image: alpine:3
    networks:
      - lal
    depends_on:
      agent:
        condition: service_healthy
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        apk add curl
        while true
        do
          curl http://agent:9999/logs/trigger
          sleep 3
        done

networks:
  lal:
